### ISSUE TITLE
MHP30 can shutdown and not enter soldering mode until it is moved

### ISSUE THREAD

**Issue by codingcatgirl** [Ralim/IronOS#1670]
When the MHP30 has not been moved for a while, it will enter shutdown mode. Once it is in this mode, attempting to enter soldering mode will immediately bring you back to the Main Menu.

The issue can be circumvented by picking up the MHP30 and moving it around to recover from the shutdown mode – or by disabling shutdown entirely.

I would have fixed this issue myself, but i am not sure why shutdown mode is a thing at all on this device, as you would expect that it is not moved for a long time while in use.

**Comment by Ralim** [comment]
Feels like a bug; the intent is that it shuts down _on movement_ (so if you knock it over it should shutdown).

**Comment by codingcatgirl** [comment]
Right, it does that too though, so there's that :)

**Comment by discip** [comment]
@codingcatgirl
What about this one?
Is this solved now?
If it is, please close it. 😊

**Comment by codingcatgirl** [comment]
Oof, no idea. My contribution to the firmware was long enough ago that i don't remember if i tried to fix it. My comment in #1570 seems to imply that i have not fixed this part of the issue however.

**Comment by discip** [comment]
> My comment in #1570 seems to imply that i have not fixed this part of the issue however.

Are you planning to solve this?

**Comment by codingcatgirl** [comment]
No, i only fixed the other part of the issue as a side effect of the new
feature i contributed.

**Comment by Ralim** [comment]
@codingcatgirl Can you confirm that your MHP30 has the MSA301 accelerometer in it?
Going to try and reproduce this shortly :)

**Comment by codingcatgirl** [comment]
Can't confirm this right now, but i am pretty sure that looking at the code this didn't look like a hardware-related issue but simply due to the fact that if there hasn't been movement in a while it will automatically exit sodlering mode again right after entering it.
